### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by richardw16** [mljs/regression-exponential#18]
Hello,

I installed image-js on my system (node v20.12.2) and encountered an error during initialization that seems related to a possible circular dependency? I'm reaching out for some assistance in resolving this issue. Here are the details:

Error Message:

class ExponentialRegression extends BaseRegression {
    ^
TypeError: Class extends value #<Object> is not a constructor or null

Steps to Reproduce:
- Install the latest version of image-js
- import { Image } from 'image-js';

Thank you for your assistance and for maintaining this useful project!

Best regards,
Richard

**Comment by targos** [comment]
@jobo322 Please have a look. This is probably because of the major updates from https://github.com/mljs/regression-exponential/commit/0db2c54a197ccefd7f29374cc976221ea94ddb94. The type definitions need to be adapted.

**Comment by richardw16** [comment]
Thanks a lot!
